### ISSUE TITLE
Throws error when requiring 'path' node module which isn't available on the browser

### ISSUE THREAD

**Issue by pheuter** [deedubs/require-jade#11]
`parseExtends` is requiring 'path' and 'fs' node modules that aren't available in the browser:

``` js
parseExtends: function(){
  var path = require('path')
    , fs = require('fs')
```

This leads to the following error being thrown when attempting to use template inheritance:

**Error: fromText eval for csmain failed: Error: failed to require "path"**

I've noticed that `exports.text` uses a variant of require to fetch 'fs':

``` js
fs = require.nodeRequire('fs');
```

But when I try to use `nodeRequire`, I get the following error:

**Object function 'require' has no method 'nodeRequire'**

Any ideas? I'm trying to use template inheritance in my jade templates that get compiled by r.js.

**Comment by DarrellBrogdon** [comment]
I'm seeing this too.

**Comment by paulyoung** [comment]
@DarrellBrogdon, see #12

**Comment by DarrellBrogdon** [comment]
Thanks!  Looks like client-side Jade isn't yet ready for prime time.

-D

**Comment by pheuter** [comment]
Consider checking out [require-j](https://github.com/pheuter/require-j)
