### ISSUE TITLE
JS error in produced optimized code

### ISSUE THREAD

**Issue by isadovskiy** [deedubs/require-jade#14]
Hello.

I have the following jade template:

textarea.note
    | #{note}

Optimizer produces the following code:

define('jade!app/view/entries-item', ['jade'], function(jade) {
    return function anonymous(locals, attrs, escape, rethrow, merge) {
        attrs = attrs || jade.attrs;
        escape = escape || jade.escape;
        rethrow = rethrow || jade.rethrow;
        merge = merge || jade.merge;
        var buf = [];
        with (locals || {}) {
            var interp;
            buf.push('<textarea class="note">' + escape((interp = note) == null ? '' : interp) + '</textarea>');
        }
        return buf.join("");
    }
});

It causes error in browser: "Uncaught TypeError: undefined is not a function" for "escape()" function. It appears not defined. Could you fix?

Thanks,
Igor

**Comment by isadovskiy** [comment]
Looks like "escape" is not propagated via "jade.escape" (escape = escape || jade.escape;)

**Comment by isadovskiy** [comment]
Some additional information. Everything works fine in optimized JS when using "excludeJade: true" build option. However if excludeJade = false, it causes runtime errors. This is because some important API is missed in this case. As I see, you need to make some additional methods exposed via jade plugin API. I made such adjustment on my end and tested. Works fine both for included and excluded Jade API. I will send updated file to you so you could review and merge the changes into git.

**Comment by isadovskiy** [comment]
Here are the patched sources:

https://docs.google.com/file/d/0B4Ec_AMB8FX2NUxxU1FfU1hzbkU/edit?usp=sharing

**Comment by vincentmac** [comment]
Could you please create a PR so I can see what has changed?

**Comment by isadovskiy** [comment]
Just did. Please review.

**Comment by vincentmac** [comment]
Please see [this comment](https://github.com/rocketlabsdev/require-jade/pull/15#issuecomment-14996215) in the [PR #15](https://github.com/rocketlabsdev/require-jade/pull/15).

**Comment by EvanCarroll** [comment]
I'm confused.. I'm also getting this error.
