### ISSUE TITLE
Wrong HTML produced when using address tag

### ISSUE THREAD

**Issue by binarykitchen** [deedubs/require-jade#27]
In my jade file I have this:

```
        p.byline
            address.author by
                a(rel="author", href="/user/john-doe") John Doe
            time(pubdate) 5/12/2013
```

But the generated HTML code looks wrong:

``` html
<p class="byline"></p>
<address class="author">by<a rel="author" href="/user/john-doe">John Doe</a></address>
<time pubdate="pubdate">5/12/2013</time>
```

but I am expecting this:

``` html
<p class="byline">
  <address class="author">by<a rel="author" href="/user/john-doe">John Doe</a></address>
  <time pubdate="pubdate">5/12/2013</time>
</p>
```

It looks like the address tag closes the parent tag too early. When I replace the address tag with span.address, then it works.

A bug?

**Comment by crissdev** [comment]
@binarykitchen Use a DIV instead of a P. P only supports inline elements, and address is a block level element.
Here's a [fiddle](http://jsfiddle.net/Ph5hx/) on this. If you replace the P with a DIV you'll get what you expected.
Use the DOM inspector to understand more.

**Comment by binarykitchen** [comment]
Oh man, thx. Suprised to learn that after 15 years of hardcore HTML + CSS, grins ...
